// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: windowmanager.proto

#include "windowmanager.pb.h"
#include "windowmanager.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* WindowManager_method_names[] = {
  "/WindowManager/RegisterBaseWindow",
};

std::unique_ptr< WindowManager::Stub> WindowManager::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WindowManager::Stub> stub(new WindowManager::Stub(channel, options));
  return stub;
}

WindowManager::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterBaseWindow_(WindowManager_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WindowManager::Stub::RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::NoneReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::WindowRequest, ::NoneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterBaseWindow_, context, request, response);
}

void WindowManager::Stub::async::RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::WindowRequest, ::NoneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterBaseWindow_, context, request, response, std::move(f));
}

void WindowManager::Stub::async::RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterBaseWindow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NoneReply>* WindowManager::Stub::PrepareAsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NoneReply, ::WindowRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterBaseWindow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NoneReply>* WindowManager::Stub::AsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterBaseWindowRaw(context, request, cq);
  result->StartCall();
  return result;
}

WindowManager::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WindowManager_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WindowManager::Service, ::WindowRequest, ::NoneReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WindowManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::WindowRequest* req,
             ::NoneReply* resp) {
               return service->RegisterBaseWindow(ctx, req, resp);
             }, this)));
}

WindowManager::Service::~Service() {
}

::grpc::Status WindowManager::Service::RegisterBaseWindow(::grpc::ServerContext* context, const ::WindowRequest* request, ::NoneReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


