// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: windowmanager.proto
#ifndef GRPC_windowmanager_2eproto__INCLUDED
#define GRPC_windowmanager_2eproto__INCLUDED

#include "windowmanager.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class WindowManager final {
 public:
  static constexpr char const* service_full_name() {
    return "WindowManager";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::NoneReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>> AsyncRegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>>(AsyncRegisterBaseWindowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>> PrepareAsyncRegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>>(PrepareAsyncRegisterBaseWindowRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>* AsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NoneReply>* PrepareAsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::NoneReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NoneReply>> AsyncRegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NoneReply>>(AsyncRegisterBaseWindowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NoneReply>> PrepareAsyncRegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NoneReply>>(PrepareAsyncRegisterBaseWindowRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterBaseWindow(::grpc::ClientContext* context, const ::WindowRequest* request, ::NoneReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NoneReply>* AsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NoneReply>* PrepareAsyncRegisterBaseWindowRaw(::grpc::ClientContext* context, const ::WindowRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterBaseWindow_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* context, const ::WindowRequest* request, ::NoneReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterBaseWindow(::grpc::ServerContext* context, ::WindowRequest* request, ::grpc::ServerAsyncResponseWriter< ::NoneReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterBaseWindow<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::WindowRequest, ::NoneReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WindowRequest* request, ::NoneReply* response) { return this->RegisterBaseWindow(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterBaseWindow(
        ::grpc::MessageAllocator< ::WindowRequest, ::NoneReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WindowRequest, ::NoneReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterBaseWindow(
      ::grpc::CallbackServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterBaseWindow<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterBaseWindow(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterBaseWindow(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterBaseWindow(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterBaseWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterBaseWindow() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WindowRequest, ::NoneReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WindowRequest, ::NoneReply>* streamer) {
                       return this->StreamedRegisterBaseWindow(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterBaseWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterBaseWindow(::grpc::ServerContext* /*context*/, const ::WindowRequest* /*request*/, ::NoneReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterBaseWindow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WindowRequest,::NoneReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterBaseWindow<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterBaseWindow<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_windowmanager_2eproto__INCLUDED
